[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules","lib"]
test = "contracts/tests"
cache_path = "forge-cache"
solc = "0.8.23"
evm_version ="shanghai"
optimizer = true
optimizer_runs = 200
[rpc_endpoints]
# mainnet = "${FOUNDRY_ETHER_RPC_URL}"
# polygon = "${FOUNDRY_POLYGON_RPC_URL}"
mainnet = "https://mainnet.infura.io/v3/67a1d3273c2b4ceeb77f2b45c87f31cc"
polygon = "https://polygon-mainnet.infura.io/v3/67a1d3273c2b4ceeb77f2b45c87f31cc"
[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { key = "${POLYGON_MAINNET_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
