[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules","lib"]
test = "contracts/tests"
cache_path = "forge-cache"
solc = "0.8.23"
evm_version ="shanghai"
optimizer = true
optimizer_runs = 999999
[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
polygon = "https://polygon-rpc.com"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
