[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules","lib"]
test = "contracts/tests"
cache_path = "forge-cache"
solc = "0.8.23"
evm_version ="shanghai"
optimizer = true
optimizer_runs = 200
[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/63a593656f46456ab99b5d50f212f236"
polygon = "https://polygon-mainnet.infura.io/v3/63a593656f46456ab99b5d50f212f236"
[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { key = "${POLYGON_MAINNET_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
